In [5]:
import numpy as np

calculate edit distance

In [5]:
def edit_distance(stringa, stringb):
    
    M = np.zeros(shape = (len(stringa)+1, len(stringb)+1))


    for row in range(M.shape[0]):
        
        for col in range(M.shape[1]):

            if row == 0:
                M[row, col]=col
                
            elif col == 0:
                M[row, col]=row
                
            elif stringa[row-1]==stringb[col-1]:
                M[row, col] = min(M[row-1, col], M[row, col-1], M[row-1, col-1])
                
            else:
                M[row, col] = min(M[row-1, col], M[row, col-1], M[row-1, col-1])+1
                
    solution = M[len(stringa), len(stringb)]
    
    return(solution, M )

In [6]:
sol, matrix = edit_distance('abcd', 'abcef')
print(matrix)
print(sol)

[[0. 1. 2. 3. 4. 5.]
 [1. 0. 1. 2. 3. 4.]
 [2. 1. 0. 1. 2. 3.]
 [3. 2. 1. 0. 1. 2.]
 [4. 3. 2. 1. 1. 2.]]
2.0


In [ ]:
calculate pathway of edit distance

* when initially creating the DP table, record the direction taken so can then use this information to back trace from solution. 
* I still don't understand this. The below solution is incorrect but it is a starting point


In [92]:
stringa = 'rfewf'
stringb = 'swedfef'
BT = np.chararray((len(stringa)+1, len(stringb)+1), itemsize = 5)
BT[:]='blan'
BT

chararray([[b'blan', b'blan', b'blan', b'blan', b'blan', b'blan',
            b'blan', b'blan'],
           [b'blan', b'blan', b'blan', b'blan', b'blan', b'blan',
            b'blan', b'blan'],
           [b'blan', b'blan', b'blan', b'blan', b'blan', b'blan',
            b'blan', b'blan'],
           [b'blan', b'blan', b'blan', b'blan', b'blan', b'blan',
            b'blan', b'blan'],
           [b'blan', b'blan', b'blan', b'blan', b'blan', b'blan',
            b'blan', b'blan'],
           [b'blan', b'blan', b'blan', b'blan', b'blan', b'blan',
            b'blan', b'blan']], dtype='|S5')

In [134]:
'''
0 = left
1=up
2=diag
'''
def edit_distance_traced(stringa, stringb):
    
    M = np.zeros(shape = (len(stringa)+1, len(stringb)+1))
    BT = np.chararray((len(stringa)+1, len(stringb)+1), itemsize = 5) 

    for row in range(M.shape[0]):
        
        for col in range(M.shape[1]):

            if row == 0:
                M[row, col]=col
                
                BT[row, col] = 'side'
            
                

                
            elif col == 0:
                M[row, col]=row
                BT[row, col] = 'side'
                
               
                

                
            elif stringa[row-1]==stringb[col-1]:
                M[row, col] = min(M[row-1, col], M[row, col-1], M[row-1, col-1])
                
                if M[row, col] == M[row-1, col]:
                    BT[row, col] = 'left'
                elif M[row, col] == M[row, col-1]:
                    BT[row, col] = 'up'
                elif M[row, col] == M[row-1, col-1]:
                    BT[row, col]= 'diag'
            else:
                M[row, col] = min(M[row-1, col], M[row, col-1], M[row-1, col-1])+1
                
                if M[row, col] == M[row-1, col]:
                    BT[row, col] = 'left'
                elif M[row, col] == M[row, col-1]:
                    BT[row, col] = 'up'
                elif M[row, col] == M[row-1, col-1]:
                    BT[row, col]= 'diag'
                
    solution = M[len(stringa), len(stringb)]
    
    return(solution, M, BT)

In [135]:
sol, matrix, traceback = edit_distance_traced('abcd', 'abde')

In [136]:
matrix

array([[0., 1., 2., 3., 4.],
       [1., 0., 1., 2., 3.],
       [2., 1., 0., 1., 2.],
       [3., 2., 1., 1., 2.],
       [4., 3., 2., 1., 2.]])

In [137]:
import pandas as pd
import seaborn as sns

In [138]:
traceback

chararray([[b'side', b'side', b'side', b'side', b'side'],
           [b'side', b'diag', b'up', b'up', b'up'],
           [b'side', b'left', b'diag', b'up', b'up'],
           [b'side', b'left', b'left', b'diag', b'up'],
           [b'side', b'left', b'left', b'left', b'up']], dtype='|S5')

In [87]:
BT[0,1] = 'e'
BT

chararray([['', b'e', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '']], dtype='|S1')

chararray([['', b'd', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '']], dtype='|S1')